# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Build stage
- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1(e22222f7-2095-4bf0-9d8e-0d6b764d6dc0)'
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# Upload to Azure Blob Storage stage
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(e22222f7-2095-4bf0-9d8e-0d6b764d6dc0)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload \
        --account-name viswamorg \
        --container-name viswastr \
        --file $(System.DefaultWorkingDirectory)/target/*.jar \
        --name testArtifact.jar